import { Server } from './types';

export const RECOMMENDED_SERVER: Server = {
  id: 'us-la',
  country: 'United States',
  city: 'Los Angeles',
  flag: '🇺🇸',
  ipPrefix: '104.25.12',
};

export const SERVERS: Server[] = [
  RECOMMENDED_SERVER,
  { id: 'us-ny', country: 'United States', city: 'New York', flag: '🇺🇸', ipPrefix: '68.183.21' },
  { id: 'ca-tr', country: 'Canada', city: 'Toronto', flag: '🇨🇦', ipPrefix: '159.203.14' },
  { id: 'gb-ld', country: 'United Kingdom', city: 'London', flag: '🇬🇧', ipPrefix: '81.19.45' },
  { id: 'de-fr', country: 'Germany', city: 'Frankfurt', flag: '🇩🇪', ipPrefix: '176.9.10' },
  { id: 'fr-pr', country: 'France', city: 'Paris', flag: '🇫🇷', ipPrefix: '92.243.8' },
  { id: 'au-sy', country: 'Australia', city: 'Sydney', flag: '🇦🇺', ipPrefix: '101.0.12' },
  { id: 'jp-tk', country: 'Japan', city: 'Tokyo', flag: '🇯🇵', ipPrefix: '125.1.55' },
  { id: 'sg-sg', country: 'Singapore', city: 'Singapore', flag: '🇸🇬', ipPrefix: '116.88.5' },
  { id: 'nl-am', country: 'Netherlands', city: 'Amsterdam', flag: '🇳🇱', ipPrefix: '185.220.101' },
  { id: 'se-st', country: 'Sweden', city: 'Stockholm', flag: '🇸🇪', ipPrefix: '195.178.180' },
  { id: 'ch-zr', country: 'Switzerland', city: 'Zurich', flag: '🇨🇭', ipPrefix: '85.203.32' },
  { id: 'in-mb', country: 'India', city: 'Mumbai', flag: '🇮🇳', ipPrefix: '103.197.152' },
  { id: 'br-sp', country: 'Brazil', city: 'São Paulo', flag: '🇧🇷', ipPrefix: '177.104.32' },
  { id: 'za-jb', country: 'South Africa', city: 'Johannesburg', flag: '🇿🇦', ipPrefix: '102.132.0' },
  { id: 'kr-sl', country: 'South Korea', city: 'Seoul', flag: '🇰🇷', ipPrefix: '211.232.160' },
  { id: 'es-md', country: 'Spain', city: 'Madrid', flag: '🇪🇸', ipPrefix: '94.242.224' },
  { id: 'it-rm', country: 'Italy', city: 'Rome', flag: '🇮🇹', ipPrefix: '89.40.12' },
  { id: 'ie-db', country: 'Ireland', city: 'Dublin', flag: '🇮🇪', ipPrefix: '178.239.168' },
  { id: 'hk-hk', country: 'Hong Kong', city: 'Hong Kong', flag: '🇭🇰', ipPrefix: '202.181.192' },
  { id: 'nz-ak', country: 'New Zealand', city: 'Auckland', flag: '🇳🇿', ipPrefix: '122.56.224' },
  { id: 'at-vi', country: 'Austria', city: 'Vienna', flag: '🇦🇹', ipPrefix: '77.81.224' },
  { id: 'be-br', country: 'Belgium', city: 'Brussels', flag: '🇧🇪', ipPrefix: '84.193.0' },
  { id: 'dk-cp', country: 'Denmark', city: 'Copenhagen', flag: '🇩🇰', ipPrefix: '93.166.0' },
  { id: 'fi-hl', country: 'Finland', city: 'Helsinki', flag: '🇫🇮', ipPrefix: '80.221.192' },
  { id: 'no-os', country: 'Norway', city: 'Oslo', flag: '🇳🇴', ipPrefix: '95.215.0' },
  { id: 'pl-wr', country: 'Poland', city: 'Warsaw', flag: '🇵🇱', ipPrefix: '83.24.0' },
  { id: 'pt-ls', country: 'Portugal', city: 'Lisbon', flag: '🇵🇹', ipPrefix: '91.196.16' },
  { id: 'ru-ms', country: 'Russia', city: 'Moscow', flag: '🇷🇺', ipPrefix: '109.248.0' },
  { id: 'tr-is', country: 'Turkey', city: 'Istanbul', flag: '🇹🇷', ipPrefix: '88.252.128' },
  { id: 'ae-db', country: 'UAE', city: 'Dubai', flag: '🇦🇪', ipPrefix: '5.230.0' },
  { id: 'mx-mc', country: 'Mexico', city: 'Mexico City', flag: '🇲🇽', ipPrefix: '187.218.0' },
  { id: 'ar-ba', country: 'Argentina', city: 'Buenos Aires', flag: '🇦🇷', ipPrefix: '190.17.64' },
];